name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Build release distributions
        run: python -m build

      - name: Verify build
        run: twine check dist/*

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: release-build
    if: github.event_name == 'release'
    timeout-minutes: 10
    permissions:
      id-token: write                       

    environment:
      name: pypi
      url: https://pypi.org/project/YOTRACO/

    steps:
      - name: Download a distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist

      - name: Publish to TestPyPI 
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.test_pypi_password }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}

      - name: Notify on failure
        if: failure()
        run: echo "Build or upload failed. Check logs."
